// Names for every code in ecb_rates, current and retired. ECB data only carries codes.
module.exports = {
  AUD: 'Australian dollar',
  BGN: 'Bulgarian lev',
  BRL: 'Brazilian real',
  CAD: 'Canadian dollar',
  CHF: 'Swiss franc',
  CNY: 'Chinese yuan renminbi',
  CYP: 'Cypriot pound',
  CZK: 'Czech koruna',
  DKK: 'Danish krone',
  EEK: 'Estonian kroon',
  EUR: 'Euro',
  GBP: 'Pound sterling',
  HKD: 'Hong Kong dollar',
  HRK: 'Croatian kuna',
  HUF: 'Hungarian forint',
  IDR: 'Indonesian rupiah',
  ILS: 'Israeli shekel',
  INR: 'Indian rupee',
  ISK: 'Icelandic krona',
  JPY: 'Japanese yen',
  KRW: 'South Korean won',
  LTL: 'Lithuanian litas',
  LVL: 'Latvian lats',
  MTL: 'Maltese lira',
  MXN: 'Mexican peso',
  MYR: 'Malaysian ringgit',
  NOK: 'Norwegian krone',
  NZD: 'New Zealand dollar',
  PHP: 'Philippine peso',
  PLN: 'Polish zloty',
  ROL: 'Romanian leu (old)',
  RON: 'Romanian leu',
  RUB: 'Russian rouble',
  SEK: 'Swedish krona',
  SGD: 'Singapore dollar',
  SIT: 'Slovenian tolar',
  SKK: 'Slovak koruna',
  THB: 'Thai baht',
  TRL: 'Turkish lira (old)',
  TRY: 'Turkish lira',
  USD: 'US dollar',
  ZAR: 'South African rand'
}
